### ISSUE TITLE
starter kit killed my meta key osx 10.6.2

### ISSUE THREAD

**Issue by russellsimpkins** [technomancy/emacs-starter-kit#14]
The starter kit appears to work fine, but it managed to kill the mapping for the meta key to my Apple (command) key. Given there's so many files, any hints as to what might be killing my key? I have tried http://emacsformacosx.com/ and the carbon release - both are affected equally. I compiled emacs from source, but that one's meta key is not mapped to the command key.

thanks
russ

**Comment by technomancy** [comment]
I don't have a Mac, so I can't test this, but it seems like it shouldn't be able to do that. If you launch Emacs with the -Q flag, it will ignore the starter kit as well as all your dotfiles; maybe you could try that to confirm what's causing the problem? Otherwise you could try asking in #emacs on freenode.

**Comment by russellsimpkins** [comment]
thanks - i'm just having newbie key confusion.

**Comment by technomancy** [comment]
OK, cool.
