### ISSUE TITLE
paredit-mode

### ISSUE THREAD

**Issue by scbunn** [technomancy/emacs-starter-kit#2]
fresh install of emacs and emacs-starter-kit. upon loading I get turn-on-paredit: Symbol's function definition is void: paredit-mode

**Comment by remvee** [comment]
http://github.com/remvee/emacs-starter-kit/commit/229b4fc58316080d8f462076731efba2929af872

**Comment by technomancy** [comment]
Fixed in 0eb65fe; thanks for the heads up.

**Comment by technomancy** [comment]
... and closing!

**Comment by Fudge** [comment]
I'm still getting this as of today.

**Comment by simon-brooke** [comment]
What worked for me was to download and install packages `libotf0` and `libm17n-0` as `dpkg` files, manually, and manually install them using `dpkg -i`. Following this, installing emacs25 (using `apt`) worked. Trying to install the `libotf0` and `libm17n-0` using `apt` had not worked, because the broken emacs25 package broke `apt`.
