### ISSUE TITLE
issues with flyspell when editing rails views

### ISSUE THREAD

**Issue by mguterl** [technomancy/emacs-starter-kit#25]
I see this over and over again when editing Rails views.

```
Starting new Ispell process [default] ...
Enabling Flyspell mode gave an error
```

How can I disable this?  Thanks.

**Comment by pjaspers** [comment]
It's in the startskist-misc.el file on line 72, comment out
(add-hook 'text-mode-hook 'turn-on-flyspell)

**Comment by mguterl** [comment]
Thanks, that seems to have helped.  I am curious if there is some recommended way to make this work besides disabling it?  Is no one else experiencing the issue?  I ask because it seems like flyspell-mode would be pretty useful.

**Comment by phren0logy** [comment]
The issue I had was that ispell was not installed. My solution was to use HomeBrew to install aspell:

brew install aspell --lang=en

then change my username.el file to include:

(setq-default ispell-program-name "aspell")

to use aspell in place of ispell.

**Comment by ghost** [comment]
I had this problem too and solved it by:
1) installing ispell
2) setting (setq-default ispell-program-name "/opt/local/bin/ispell")

Step #2 was the most important since I'm running on OS X using darwin ports and everything GNU-ish is installed under /opt. Emacs was not looking there for the ispell program.

I don't know how to solve this problem generally as I'm new to emacs. I tried adding /opt/local/bin to the load-path instead of setting ispell-program-name but that didn't work.

**Comment by technomancy** [comment]
Sounds like this is the old OS X GUI $PATH bug striking again.
