### ISSUE TITLE
C-x <RET> brings up M-x in minibuffer

### ISSUE THREAD

**Issue by aguynamedben** [technomancy/emacs-starter-kit#43]
Trying to change my text encoding a la http://www.gnu.org/software/emacs/manual/html_node/emacs/Text-Coding.html.

When I hit C-x <RET>, the minibuffer is rewritten with M-x, so that when I type f, I am about to run M-x f.  Is this a "shortcut" of emacs starter kit?  I'm not a LISP pro, but I have been grepping all over emacs starter kit and can't find it.

Thanks for your help.

-Ben

**Comment by technomancy** [comment]
Yes, this is a starter-kit binding intended to help when you're SSHing from a mobile device since normally those have Ctrl keys but not meta. You can use M-x set-buffer-file-coding-system or use global-set-key to give it a new binding. There are a few built-in shortcuts the starter kit stomps on; this is just due to the fact that there are only so many keys on the keyboard and basically an infinite number of Emacs commands.
